from random import choice

nouns = [
    "factory reset button",
    "blood rage",
    "idiot",
    "toaster",
    "legend",
    "death wish",
    "therapy",
    "goal in life",
    "marketing idea",
    "psychic",
    "knife",
    "sandwich",
    "hunting ground",
    "lettuce",
    "kitty",
    "friendly grandma",
    "french chef",
    "antidepressant drug",
    "corn cake",
    "president of the night",
    "candlestick maker",
    "coffee pot",
    "brethren",
    "national security agency",
    "tank",
    "useless brakes",
    "international law enforcement agency",
    "sound barrier",
    "skinny woman",
    "private investor",
    "main people",
    "stock car",
    "elastic band",
    "whole blood",
    "telephone",
    "mad cow disease",
    "scourge upon the earth",
    "skinned newt",
    "karate",
    "pistol",
    "legal warrant",
    "people who are hurt",
    "idea he suggested",
    "party",
    "place of business",
    "double fault",
    "kitty cat",
    "famous landscape painting",
    "hairy legs",
    "old irish cottage",
    "pocket flask",
    "liquid oxygen",
    "laser beams",
    "preventive strike",
    "dingle berry",
    "reading party",
    "generalized bond",
    "indirect expression",
    "messiness",
    "love of her life",
    "trust fund",
    "volcanic crater",
    "travel guidebook",
    "electric furnace",
    "internal respiration",
    "police squad",
    "mad - dog skullcap",
    "sneaky criminal",
    "new version",
    "keepsake machete",
    "gaming laptop",
    "hissy fit",
    "dog poop",
    "dragon",
    "mediation",
    "patrolman",
    "pervert",
    "toilet seat",
    "haunted graveyard",
    "really tough guy",
    "twinkling uncleanness",
    "wrinkle",
    "personal credit line",
    "multi - billionaire",
    "mental disorder",
    "sweet tailpipe",
    "boiling water",
    "deer antler",
    "background story",
    "striped hyena",
    "weed whacker",
    "backstabbing misfortune",
    "bad striped hyena",
    "bat - shit crazy Amish folk",
    "beautiful elastic band",
    "best failure",
    "big - bellied bad mood",
    "bitchy peace offering",
    "bloody indignation",
    "bone - chilling legal warrant",
    "boring heartbreak",
    "bottle - conditioned trainer",
    "bottled sweet tailpipe",
    "brainless ways of the world",
    "brewery - fresh sleazeball",
    "bright - eyed double fault",
    "brokenhearted druggie",
    "bull - headed lover",
    "busty descending color",
    "buxom personality",
    "cask - conditioned freak",
    "cat - friendly reading party",
    "caught -in -the - act jackass",
    "chauvinistic pup",
    "cheap natural history",
    "cheeky keepsake machete",
    "cheerful toilet seat",
    "chilled good - for - nothing",
    "chunky drug addict",
    "cocky matrimonial law",
    "cold - hearted Eskimo",
    "colored snuggle bug",
    "colossal love of her life",
    "comforting grouch",
    "comic divergent thinking",
    "common toilet seat",
    "compassionate bad mood",
    "complex guilt",
    "confrontational freak",
    "considerate louse",
    "contemporary queen",
    "content dirtbag",
    "crawly mistake",
    "crazed master",
]

verbs = [
    "surround",
    "stab",
    "return",
    "medicate",
    "blindside",
    "boogie",
    "flap",
    "trip",
    "swat",
    "suck",
    "harass",
    "trap",
    "snoop",
    "explode",
    "sketch",
    "scatter",
    "challenge",
    "fight",
    "bury",
    "splatter",
    "smack",
    "peddle",
    "balance",
    "trip up",
    "boggle",
    "poke",
    "critique",
    "fear",
    "initiate",
    "line up",
    "run over",
    "schedule",
    "cook",
    "imprison",
    "underestimate",
    "cajole",
    "wheedle",
    "soft soap",
    "butter up",
    "sweet - talk",
    "prevail",
    "shred",
    "drink",
    "dispute",
    "echo",
    "mimic",
    "berate",
    "castigate",
    "underrate",
    "taunt"
]

adjectives = [
    "dead",
    "hairless",
    "sadistic",
    "metal",
    "wild",
    "domesticated",
    "abnormal",
    "medicated",
    "cocky",
    "massive",
    "disrespectful",
    "impressive",
    "out of control",
    "internet worthy",
    "hilarious",
    "sexy",
    "hot",
    "very tactful",
    "bearded",
    "duck - like",
    "violent",
    "slimy",
    "insanely creepy",
    "embarrassed to the bone",
    "self - centered",
    "talking",
    "naked",
    "angry",
    "shaky",
    "deep",
    "sick",
    "zippy",
    "sticky",
    "fluffy",
    "frozen",
    "unholy",
    "painfully honest",
    "filthy",
    "fighting",
    "bonkers",
    "harsh",
    "frisky",
    "greedy",
    "crawly",
    "insane",
    "hideous",
    "ungodly",
    "abusive",
    "drunken",
    "hateful",
    "idiotic",
    "twisted",
    "useless",
    "yapping",
    "magical",
    "indecent",
    "godawful",
    "arrogant",
    "confused",
    "flirting",
    "high - end",
    "insecure",
    "maniacal",
    "sickened",
    "slippery",
    "stubborn",
    "tripping",
    "vengeful",
    "sinister",
    "costumed",
    "cowardly",
    "haunting",
    "startled",
    "alcoholic",
    "demanding",
    "shivering",
    "offensive",
    "nighttime",
    "startling",
    "disgusting",
    "slap happy",
    "disturbing",
    "adulterous",
    "blathering",
    "flickering",
    "rebellious",
    "impertinent",
    "bull headed",
    "hyperactive",
    "infuriating",
    "outnumbered",
    "pea - brained",
    "territorial",
    "underhanded",
    "zombie like",
    "mischievous",
    "at - the - ready",
    "free - loading",
    "house - broken",
    "up - to - no - good",
    "cruel - hearted",
    "misunderstood",
    "narrow - minded",
    "self - absorbed",
    "bat - shit - crazy",
    "fiercely - loyal",
    "out - of - control",
    "fear - inspiring",
    "bat shit crazy",
    "mentally impaired",
]

def madlib():
    return f'the {choice(adjectives)} {choice(nouns)} {choice(verbs)} the {choice(nouns)}'

print(madlib())